### ISSUE TITLE
自定义顶部导航会被键盘挤上去问题

### ISSUE THREAD

**Issue by StruggleThunder** [wechat-miniprogram/navigation-bar#3]
在真机上（安卓、苹果都试了） 自定义顶部导航区域都会被键盘给挤上去。

**Comment by JuneAndGreen** [comment]
能否给个问题截图，并描述一下你期望的效果？

**Comment by StruggleThunder** [comment]
> 能否给个问题截图，并描述一下你期望的效果？
![wxnavissue001](https://user-images.githubusercontent.com/29719722/48499283-1110d900-e873-11e8-80ac-47ba534ed576.jpg)

![wxnavissue002](https://user-images.githubusercontent.com/29719722/48499320-2423a900-e873-11e8-811f-421e4e02c243.jpg)

在源代码上只加了一个文本框。点击文本框出现的键盘会把自定义导航区域给挤上去。  

>自定义顶部导航  不只是会被键盘挤上去的问题，在真机上 `<video>`  和  `<canvas>` 标签的内容都会压在自定义导航区域的上层。

**Comment by JuneAndGreen** [comment]
明白问题了，video 和 canvas 等属于原生组件，层级最高，所以目前是肯定会盖在自定义导航栏上面的，后续会上一个叫“同层渲染”的功能，应该可以解决原生组件层级问题。

input 上推这个目前只能禁掉上推来处理了，input 有个 adjust-position 属性，设置为 false 即可。这里的上推是会将承载渲染的整个 webview 上推，所以目前除了禁止上推外暂时没有比较好的解决方案了。

**Comment by StruggleThunder** [comment]
知道了，感谢
