### ISSUE TITLE
下拉刷新android系统会把整个navigation-bar拉下去

### ISSUE THREAD

**Issue by mengshixing** [wechat-miniprogram/navigation-bar#5]

**Comment by JuneAndGreen** [comment]
安卓这是正常的表现，iOS 没有把 fixed 项目拉下去是有问题的。navigation-bar 本身是自定义组件，属于
 webview 里渲染的，而这里的下拉是整个 webview 下拉，理论是应该将 navigation-bar 拉下去才正常。

**Comment by mengshixing** [comment]
ok　谢谢
